# Site settings
title:       Quaintous
email:
author:      Yan Foto
description: "Too many MCs, not enought mics"
baseurl:     ""
url:         "https://blog.quaintous.com"
language: en

# Social icons
show_social_icons: true
github_username: yan-foto
stackoverflow_id: 2295964
twitter_username: "@quaintous"
google_plus_id:
linkedin_username:
angellist_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
permalink:    /:year/:month/:day/:title/
paginate:     3
sass:
  compressed: true
gems: [jekyll-paginate]
